version: '3.7'

services:
  jenkins:
    image: jenkinswithjmeter
    build:
      context: jenkins/
    volumes:
      - type: volume
        source: jenkins
        target: /var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks: 
      - loadtests

  jmeterserver1:
    image: jmeter
    build:
      context: jmeter/
    networks: 
      - loadtests
  
  jmeterserver2:
    image: jmeter
    networks: 
      - loadtests
  
  web:
    image: web
    build:
      context: web/
    networks: 
      - loadtests

networks:
  loadtests:
    driver: bridge

volumes:
  jenkins:
